# Generated by Django 4.2 on 2023-04-26 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_a', '0002_usermodels_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModels',
        ),
    ]
