# Generated by Django 4.2 on 2023-04-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_a', '0008_remove_cartitem_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.DecimalField(decimal_places=1, default=-1.0, max_digits=8),
            preserve_default=False,
        ),
    ]
